routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('cells');
});

Route::resource('cells', 'CellsController');

app/Cell.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cell extends Model
{
    protected $fillable = ['title', 'hyperlink', 'position', 'color_id'];

    public static $availablePositionsStart = 0;
    public static $availablePositionsEnd = 8;

    /**
     * The color of the cell.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function color() {
        return $this->belongsTo(Color::class);
    }

    /**
     * Gets the available cells.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public static function available() {
        return self::with('color')->whereBetween('position', [self::$availablePositionsStart, self::$availablePositionsEnd])->get()->keyBy('position');
    }
}

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $fillable = ['name', 'hex_code'];

    public function cells() {
        return $this->hasMany(Cell::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CellsController.php
<?php

namespace App\Http\Controllers;

use App\Cell;
use App\Color;


class CellsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $cells = Cell::available();
        return view('cells.index', [
            'cells' => $cells,
            'maxPosition' => Cell::$availablePositionsEnd
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        $colors = Color::all();
        $request = $this->validatePosition();
        return view('cells.create', ['colors' => $colors, 'position' => $request['position']]);
    }

    /**
     * Store a newly created resource in storage.
     *
     */
    public function store()
    {
        Cell::create($this->validateRequest());
        return redirect(route('cells.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param Cell $cell
     */
    public function show(Cell $cell)
    {
        return redirect(route('cells.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     */
    public function edit(Cell $cell)
    {
        $colors = Color::all();
        return view('cells.edit', ['cell' => $cell, 'colors' => $colors]);
    }

    /**
     * Update the specified resource in storage.
     *
     */
    public function update(Cell $cell)
    {
        $cell->update($this->validateRequest());
        return redirect(route('cells.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     */
    public function destroy(Cell $cell)
    {
        $cell->delete();
        return redirect(route('cells.index'));
    }

    /**
     * Validate the request attributes.
     *
     * @return array
     */
    protected function validateRequest()
    {
        return request()->validate([
            'title' => 'required',
            'hyperlink' => 'required|url|active_url',
            'position' => 'sometimes|required|unique:cells,position|integer|between:'.Cell::$availablePositionsStart.','.Cell::$availablePositionsEnd,
            'color_id' => 'required|exists:colors,id'
        ]);
    }
    /**
     * Validate the position parameter.
     *
     * @return array
     */
    protected function validatePosition()
    {
        return request()->validate([
            'position' => 'required|unique:cells,position|integer|between:'.Cell::$availablePositionsStart.','.Cell::$availablePositionsEnd
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cells/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="form-wrapper">
        <form action="{{ route('cells.store') }}" method="POST">

            @include('cells.form')

            <div class="input-group">
                <button type="submit" class="submit">Create!</button>
            </div>
        </form>
    </div>
@endsection

resources/views/cells/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="form-wrapper">
        <form action="{{ route('cells.update', ['cell' => $cell]) }}" method="POST" id="form-update">
            @method('PUT')

            @include('cells.form')

        </form>
        <form action="{{ route('cells.destroy', ['cell' => $cell]) }}" id="form-delete" method="POST">
            @csrf
            @method('DELETE')
        </form>
        <div class="input-group">
            <button type="submit" class="submit" form="form-update">Update!</button>
            <button type="submit" class="submit delete" form="form-delete"
                    onclick="confirm('Are you sure you want to delete it?')">
                Delete!
            </button>
        </div>
    </div>
@endsection

resources/views/cells/form.blade.php
@csrf
<div class="input-group">
    @if(isset($position))
        <input type="hidden" value="{{ $position }}" name="position">
        @error('position')
        <div class="danger">{{ $message }}</div>
        @enderror
    @endif
</div>
<div class="input-group">
    <label for="title">Title:</label>
    <input id="title" type="text" name="title" value="{{ old('title', $cell->title ?? '') }}" required
           placeholder="Sample Title"
           class="@error('title') invalid @enderror">
    @error('title')
        <div class="danger">{{ $message }}</div>
    @enderror
</div>
<div class="input-group">
    <label for="hyperlink">Hyperlink:</label>
    <input id="hyperlink" type="text" name="hyperlink" value="{{ old('hyperlink', $cell->hyperlink ?? '') }}" required
           placeholder="https://example.com/"
           class="@error('hyperlink') invalid @enderror">
    @error('hyperlink')
        <div class="danger">{{ $message }}</div>
    @enderror
</div>
<div class="input-group">
    <label for="color">Color:</label>
    @foreach($colors as $color)
        <input type="radio"
               name="color_id"
               id="c{{ $color->id }}"
               value="{{ $color->id }}"
               @if (old('color_id', $cell->color_id ?? '') == $color->id) checked @endif>
        <label for="c{{ $color->id }}" style="background-color: {{ $color->hex_code }}" class="color"></label>
    @endforeach
    @error('color_id')
        <div class="danger">{{ $message }}</div>
    @enderror
</div>

resources/views/cells/index.blade.php
@extends('layouts.app')

@section('content')
    @for ($i = 0; $i <= $maxPosition; $i++)
        <div class="cell">
            @if(isset($cells[$i]))
               <a href="{{ $cells[$i]->hyperlink }}"
                  class="has-link link"
                  target="_blank"
                  style="background-color: {{$cells[$i]->color->hex_code}}"
               >
                   go
               </a>
                <a href="{{ route('cells.edit', ['cell' => $cells[$i]]) }}" class="edit">settings</a>
            @else
                <a href="{{ route('cells.create', ['position' => $i ]) }}" class="empty link">+</a>
            @endif
        </div>
    @endfor
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SHKOLO task</title>
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
</head>
<body>
    <header class="app-header">
    </header>
    <div class="app-wrapper">
        <div class="board-wrapper">
            <div id="scratch1" class="scratch"></div>
            <div id="scratch2" class="scratch"></div>
            <div id="scratch3" class="scratch"></div>
            <div id="scratch4" class="scratch"></div>
            @yield('content')
        </div>
    </div>
    <footer>

    </footer>
</body>
</html>